### ISSUE TITLE
Please push changes of 2.3.2.4

### ISSUE THREAD

**Issue by khibino** [hdbc/hdbc-postgresql#41]
The newest version uploaded to hackage is 2.3.2.4 ( http://hackage.haskell.org/package/HDBC-postgresql-2.3.2.4 ), but head of this repository is 2.3.2.3.

**Comment by khibino** [comment]
May I make pull request?

**Comment by hesselink** [comment]
Oh, that's very sloppy, sorry! I just pushed the changes.
